// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Actions(arg1) {
  return window['go']['plugins']['Manager']['Actions'](arg1);
}

export function Call(arg1, arg2) {
  return window['go']['plugins']['Manager']['Call'](arg1, arg2);
}

export function LoadPlugins() {
  return window['go']['plugins']['Manager']['LoadPlugins']();
}

export function MakeAction(arg1) {
  return window['go']['plugins']['Manager']['MakeAction'](arg1);
}

export function Plugins() {
  return window['go']['plugins']['Manager']['Plugins']();
}

export function RightPanels() {
  return window['go']['plugins']['Manager']['RightPanels']();
}
