// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugins} from '../models';

export function Actions(arg1:string):Promise<{[key: string]: any}>;

export function Call(arg1:string,arg2:any):Promise<any>;

export function LoadPlugins():Promise<Error>;

export function MakeAction(arg1:string):Promise<any>;

export function Plugins():Promise<Array<plugins.Plugin>>;

export function RightPanels():Promise<Array<plugins.PanelEntry>>;
