// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bind(arg1) {
  return window['go']['api']['Api']['Bind'](arg1);
}

export function GetBuffer(arg1) {
  return window['go']['api']['Api']['GetBuffer'](arg1);
}

export function GetBufferNames() {
  return window['go']['api']['Api']['GetBufferNames']();
}

export function GetCursor(arg1) {
  return window['go']['api']['Api']['GetCursor'](arg1);
}

export function HandleKeyboardEvent(arg1) {
  return window['go']['api']['Api']['HandleKeyboardEvent'](arg1);
}

export function LengthOfBuffer(arg1) {
  return window['go']['api']['Api']['LengthOfBuffer'](arg1);
}

export function LengthOfLine(arg1) {
  return window['go']['api']['Api']['LengthOfLine'](arg1);
}

export function SetCursor(arg1) {
  return window['go']['api']['Api']['SetCursor'](arg1);
}
