// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {plugins} from '../models';
import {types} from '../models';

export function Bind(arg1:core.Core):Promise<void>;

export function CloseFile(arg1:string):Promise<Error>;

export function GetActionsList(arg1:string):Promise<Array<plugins.Action>>;

export function GetBuffer(arg1:string):Promise<types.BufferData>;

export function GetBufferNames():Promise<Array<string>>;

export function GetCursor(arg1:string):Promise<types.GetCaretResponse>;

export function GetPanelTabs():Promise<Array<string>>;

export function GetRightPanels():Promise<Array<plugins.PanelEntry>>;

export function HandleKeyboardEvent(arg1:{[key: string]: any}):Promise<Error>;

export function LengthOfBuffer(arg1:string):Promise<number>;

export function LengthOfLine(arg1:types.GetLineLengthRequest):Promise<number>;

export function MouseDown(arg1:{[key: string]: any}):Promise<Error>;

export function MouseUp(arg1:{[key: string]: any}):Promise<Error>;

export function SetCursor(arg1:{[key: string]: any}):Promise<types.GetCaretResponse>;
