// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bind(arg1) {
  return window['go']['api']['Api']['Bind'](arg1);
}

export function CloseFile(arg1) {
  return window['go']['api']['Api']['CloseFile'](arg1);
}

export function GetActionsList(arg1) {
  return window['go']['api']['Api']['GetActionsList'](arg1);
}

export function GetBuffer(arg1) {
  return window['go']['api']['Api']['GetBuffer'](arg1);
}

export function GetBufferNames() {
  return window['go']['api']['Api']['GetBufferNames']();
}

export function GetCursor(arg1) {
  return window['go']['api']['Api']['GetCursor'](arg1);
}

export function GetPanelTabs() {
  return window['go']['api']['Api']['GetPanelTabs']();
}

export function GetRightPanels() {
  return window['go']['api']['Api']['GetRightPanels']();
}

export function HandleKeyboardEvent(arg1) {
  return window['go']['api']['Api']['HandleKeyboardEvent'](arg1);
}

export function LengthOfBuffer(arg1) {
  return window['go']['api']['Api']['LengthOfBuffer'](arg1);
}

export function LengthOfLine(arg1) {
  return window['go']['api']['Api']['LengthOfLine'](arg1);
}

export function MouseDown(arg1) {
  return window['go']['api']['Api']['MouseDown'](arg1);
}

export function MouseUp(arg1) {
  return window['go']['api']['Api']['MouseUp'](arg1);
}

export function SetCursor(arg1) {
  return window['go']['api']['Api']['SetCursor'](arg1);
}
